# Generated by Django 4.2.30 on 2026-05-30 02:50

import app.models.base_model
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, default=app.models.base_model.generate_uid, editable=False, help_text='Short, URL-friendly unique identifier.', max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, default=app.models.base_model.generate_uid, editable=False, help_text='Short, URL-friendly unique identifier.', max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='password')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user-agent')),
                ('path', models.TextField(blank=True, null=True, verbose_name='path')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('session_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='session key')),
            ],
            options={
                'verbose_name': 'login attempt',
                'verbose_name_plural': 'login attempts',
                'ordering': ('-created_date',),
            },
        ),
    ]
