# Generated by Django 4.2.30 on 2026-05-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='Empty', editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='password')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='user-agent')),
                ('path', models.TextField(blank=True, null=True, verbose_name='path')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('session_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='session key')),
            ],
            options={
                'verbose_name': 'login attempt',
                'verbose_name_plural': 'login attempts',
                'ordering': ('-created_date',),
            },
        ),
    ]
