version: 0.2

env:
  variables:
    DOCKERFILE: "aws.Dockerfile"
    DOCKER_BUILDKIT: "1"
    IMAGE_TAG: "test"

phases:
  pre_build:
    commands:
      # Log in to ECR
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

  build:
    commands:
      - bash scripts/ecs-deploy build --tag "$IMAGE_TAG"

  post_build:
    commands:
      - bash scripts/ecs-deploy deploy
