# Generated by Django 4.2.30 on 2026-05-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("threads", "0001_initial"),
        ("masks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default="Empty",
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the reaction",
                        max_length=250,
                        unique=True,
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        help_text="Reaction icon",
                        upload_to="reactions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReactionRelation",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default="Empty",
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "mask",
                    models.ForeignKey(
                        help_text="Mask",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masks.mask",
                    ),
                ),
                (
                    "reaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reactions.reaction",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="Reaction thread",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="threads.thread",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
