# Django
from django.db.models import Count, Q, Sum
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import GenericViewSet
from rest_framework.status import HTTP_200_OK, HTTP_404_NOT_FOUND

# Models
from app.models.mask import Mask
from app.models.thread import Thread

# Serializers
from app.rest.serializers.mask_profile_serializer import \
    MaskProfileSerializer

# Libs
from app.permissions.client import IsClientAuthenticated


class MasksViewSet(GenericViewSet):
    """
    GET /users/<hash>/ → { mask_id, joined, posts_count, replies_count }

    Mask hover card data. Efficient: both counts are ANNOTATED in the same
    query (Count with filter) — a single query, no N+1:
      - posts_count   = the user's ROOT threads (sub is null), active and
                        visible (same criteria as the feed)
      - replies_count = the user's replies (sub not null), active

    E2E encryption comes from the default renderer (EncodeRenderer when
    ENCRYPTED_RESPONSE), which already serializes datetime with DRF's
    JSONEncoder. Nonexistent hash → 404.
    """

    queryset = Mask.objects.filter(is_active=True)
    serializer_class = MaskProfileSerializer
    permission_classes = (IsClientAuthenticated,)

    def retrieve(self, request, pk) -> Response:
        mask = get_object_or_404(
            Mask.objects.filter(is_active=True, hash=pk).annotate(
                posts_count=Count(
                    "thread",
                    filter=Q(
                        thread__is_active=True,
                        thread__visibility=True,
                        thread__sub__isnull=True,
                    ),
                    distinct=True,
                ),
                replies_count=Count(
                    "thread",
                    filter=Q(
                        thread__is_active=True,
                        thread__sub__isnull=False,
                    ),
                    distinct=True,
                ),
            )
        )
        serializer = MaskProfileSerializer(mask)
        return Response(serializer.data, status=HTTP_200_OK)


class CurrentMaskView(APIView):
    """
    GET /me/ — the CURRENT user's mask (request.mask, which the
    MaskMiddleware resolves on each request). PRIVATE (IsClientAuthenticated,
    same as the rest) + E2E encryption (default renderer).

    Lightweight on purpose: only IDENTITY (mask_id). The avatar is generated by
    the frontend with MaskAvatar from the id (procedural, no uploads).
    Extensible for the future own Profile (add fields here).
    """

    permission_classes = (IsClientAuthenticated,)

    def get(self, request) -> Response:
        mask = getattr(request, "mask", None)
        if mask is None:
            return Response({"detail": "No mask."}, status=HTTP_404_NOT_FOUND)
        return Response({
            "mask_id": mask.hash,
            # Reader's region (middleware's GeoIP): the FE forwards it
            # to For You (?region=) for the regional boost. The BA
            # re-validates it against GeoIP on each request — declarative.
            "country_code": mask.country_code or "",
            # PRIVATE stats — only returned here, for the owner's own /me. A
            # SINGLE aggregate over the user's threads, no joins to the
            # reaction/reply tables: it reuses the precomputed momentum counters
            # (unique_reactors_count / unique_commenters_count, both excluding
            # the author). Cheap on limited hardware, no N+1.
            #   threads   = the user's ROOT threads (sub is null)
            #   reactions = reactions received across all their posts (the
            #               reaction model is one-per-user → distinct reactors
            #               == total reactions)
            #   replies   = distinct people who replied to their posts
            "stats": self._owner_stats(mask),
        })

    @staticmethod
    def _owner_stats(mask) -> dict:
        agg = Thread.objects.filter(mask=mask, is_active=True).aggregate(
            threads=Count("id", filter=Q(sub__isnull=True)),
            reactions=Sum("unique_reactors_count"),
            replies=Sum("unique_commenters_count"),
        )
        return {
            "threads": agg["threads"] or 0,
            "reactions": agg["reactions"] or 0,
            "replies": agg["replies"] or 0,
        }
