# Python
import secrets

# Django
from django.conf import settings
from rest_framework.viewsets import GenericViewSet
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.generics import get_object_or_404
from rest_framework.status import (
    HTTP_200_OK,
    HTTP_201_CREATED,
    HTTP_400_BAD_REQUEST,
    HTTP_413_REQUEST_ENTITY_TOO_LARGE,
)

# Models
from app.models.media import ThreadFile
from app.models.thread import Thread

# Libs
from app.permissions.client import IsClientAuthenticated
from app.permissions.captcha import human_validator
from app.constants.threads import UPLOAD_CONTENT_TYPE_EXT
from app.methods.storage_backends import get_backend, build_object_key
from app.rest.serializers.thread_file_serializer import (
    PresignSerializer,
    ConfirmSerializer,
    clean_metadata,
)


class ThreadFilesViewSet(GenericViewSet):
    """Direct-to-storage media upload, decoupled from posting (3 steps).

    The binary NEVER passes through the backend's models: the client uploads it
    straight to storage with the URL the adapter returns, AS SOON AS compression
    + NSFW finish — before the thread exists. So:

      1. presign  — no thread; creates a DETACHED pending record bound to the
                    requester's mask (thread=NULL, is_active=False).
      2. PUT       — client uploads to the returned URL (with progress).
      3. confirm   — at Send, once the thread exists: verifies the object exists,
                    attaches it to the thread (owned by the same mask), stores
                    the config metadata and activates it.

    The storage adapter (storage_backends.get_backend) returns a REAL R2
    presigned URL when R2 is configured, or a local backend URL when running in
    DEBUG without storage — the FE contract is identical either way.

    Both endpoints ride the standard transport (E2E crypto + rotating gateway)
    and require the single-request ticket (IsClientAuthenticated). Ownership is
    enforced server-side via the mask on both the pending file and the thread.
    """

    queryset = ThreadFile.objects.all()
    permission_classes = (IsClientAuthenticated,)

    @action(detail=False, methods=["post"], url_path="presign")
    @human_validator
    def presign(self, request) -> Response:
        """
        Step 1 — issue an upload URL. No thread yet: the file is uploaded before
        the thread is created.
        ---
        Request Body:

                {
                    "content_type": "image/webp | image/png | image/jpeg | video/mp4",
                    "is_video": false,
                    "filename_original": "optional"
                }

        Response (201):

                {
                    "upload_url": "<PUT URL (R2 presigned or local)>",
                    "method": "PUT",
                    "headers": {"Content-Type": "<content_type>"},
                    "key": "uploads/<uid>.<ext>",
                    "uid": "<file uid>",
                    "public_url": "<public URL>",
                    "expires_in": <seconds>
                }

        The PUT must use the SAME Content-Type returned in `headers`.

        Codes: 201 created (detached) · 400 invalid · 401 unauthorized.
        """
        serializer = PresignSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.validated_data

        backend = get_backend()
        ext = UPLOAD_CONTENT_TYPE_EXT[data["content_type"]]
        # The object name is a LONG cryptographically-random token — NOT the
        # uid or id — so the public URL is not guessable/enumerable (a
        # capability URL, Meta/Instagram style). ~43 URL-safe chars.
        token = secrets.token_urlsafe(32)
        # Sharded key: 'm/<c1c2>/<c3c4>/<token>.<ext>' (organizational only; the
        # token is what makes it non-guessable). The object stays at this key;
        # confirm only attaches the relation — no copy/rename needed.
        key = build_object_key(token, ext)

        # Auto-detected backend origin (no env var): the local adapter uses it
        # to build absolute URLs; R2 ignores it.
        base_url = request.build_absolute_uri("/")
        # The public URL is already known here (it's deterministic from the
        # key), so persist it NOW. This way a pending upload that never gets
        # confirmed (user uploaded but didn't post) still has its URL on record
        # instead of being an orphan you'd have to look up in Cloudflare.
        public_url = backend.public_url(key, base_url=base_url)

        # Detached pending record (thread=NULL, is_active=False) bound to the
        # uploader's mask, so confirm can only attach files THIS mask uploaded.
        # uid is auto-generated by BaseModel (external id, decoupled from the
        # object name).
        thread_file = ThreadFile.objects.create(
            file_key=key,
            file_url=public_url,
            mask=request.mask,
            thread=None,
            is_video=data["is_video"],
            is_active=False,
        )

        upload = backend.generate_upload(key, data["content_type"], base_url=base_url)

        return Response(
            {
                "upload_url": upload["upload_url"],
                "method": upload["method"],
                "headers": upload["headers"],
                "key": key,
                "uid": thread_file.uid,
                "public_url": public_url,
                "expires_in": upload["expires_in"],
            },
            status=HTTP_201_CREATED,
        )

    @action(detail=False, methods=["post"], url_path="confirm")
    @human_validator
    def confirm(self, request) -> Response:
        """
        Step 3 — at Send: verify the object exists, attach it to the thread,
        store metadata and activate.
        ---
        Request Body:

                {
                    "uid": "<file uid from presign>",
                    "thread": "<thread public uid>",
                    "is_video": false,
                    "width": 1408,
                    "height": 2112,
                    "target_color": "#060503",
                    "is_nsfw": true,
                    "metadata": { ...config attributes... }
                }

        width/height/target_color are NOT columns anymore — they are stored
        INSIDE `metadata`. The object MUST exist (verified by the adapter) before
        the record is activated.

        Codes: 200 confirmed · 400 invalid / object missing / too large ·
        401 unauthorized · 404 pending file or thread not found / not owned.
        """
        serializer = ConfirmSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.validated_data

        backend = get_backend()

        # The DETACHED pending record this mask uploaded (not yet attached).
        thread_file = get_object_or_404(
            ThreadFile,
            uid=data["uid"],
            mask=request.mask,
            thread__isnull=True,
            is_active=False,
        )

        # The thread to attach it to — must exist and belong to the same mask.
        thread = get_object_or_404(Thread, uid=data["thread"], is_active=True, mask=request.mask)

        key = thread_file.file_key

        # Verify the object actually exists in storage before activating.
        head = backend.object_exists(key)
        if head is None:
            return Response(
                {"detail": "Uploaded object not found in storage."},
                status=HTTP_400_BAD_REQUEST,
            )

        # General hard cap for ANY file (the real, untrusted-client guard). The
        # actual object size from storage — can't be spoofed by the client.
        size = head.get("content_length") or 0
        if size > settings.UPLOAD_MAX_BYTES:
            return Response(
                {"detail": "Uploaded object is too large."},
                status=HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            )

        # Content-type family must match the declared media kind, when storage
        # reports it (R2 does; local disk doesn't).
        content_type = head.get("content_type") or ""
        expected_prefix = "video/" if data["is_video"] else "image/"
        if content_type and not content_type.startswith(expected_prefix):
            return Response(
                {"detail": "Uploaded object type does not match."},
                status=HTTP_400_BAD_REQUEST,
            )

        # Dimensions + dominant color now live INSIDE metadata (no columns).
        metadata = clean_metadata(data["metadata"])
        metadata["width"] = data["width"]
        metadata["height"] = data["height"]
        metadata["target_color"] = data["target_color"]

        # Full public URL — same base as the presign's public_url (R2: the
        # configured domain; local: auto-detected from the request), so
        # file_url == that public_url. Persisted for the client; file_key stays
        # internal (storage ops like deletion).
        public_url = backend.public_url(key, base_url=request.build_absolute_uri("/"))

        # Attach to the thread, store the reference + URL + metadata, activate.
        thread_file.thread = thread
        thread_file.file_url = public_url
        thread_file.is_video = data["is_video"]
        thread_file.is_nsfw = data["is_nsfw"]
        thread_file.metadata = metadata
        thread_file.is_active = True
        thread_file.save()

        return Response(
            {
                "uid": thread_file.uid,
                "key": key,
                "public_url": public_url,
                "file_url": public_url,
                "is_video": thread_file.is_video,
                "is_nsfw": thread_file.is_nsfw,
                "metadata": thread_file.metadata,
            },
            status=HTTP_200_OK,
        )
