
VIDEO_FORMAT = "video"
UNKNOWN_MEDIA_FORMAT = "Unknown"

ALLOWED_VIDEO_FORMAT = ("mp4", )
ALLOWED_IMAGE_FORMAT = (
    'png',
    'jpg',
    'jpeg'
)

ALLOWED_MEDIA_FORMATS = ALLOWED_VIDEO_FORMAT + ALLOWED_IMAGE_FORMAT
