# Generated by Django 4.2.30 on 2026-06-04 20:51

import app.models.base_model
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_enable_unaccent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=app.models.base_model.generate_uid,
                        editable=False,
                        help_text="Short, URL-friendly unique identifier.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("hash", models.CharField(max_length=250, unique=True)),
                ("country_code", models.CharField(help_text="Country of mask", max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Miniature",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=app.models.base_model.generate_uid,
                        editable=False,
                        help_text="Short, URL-friendly unique identifier.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250, unique=True)),
                ("icon", models.ImageField(help_text="Mask miniature icon", upload_to="miniature")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=app.models.base_model.generate_uid,
                        editable=False,
                        help_text="Short, URL-friendly unique identifier.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Name of the reaction", max_length=250, unique=True)),
                ("emoji", models.CharField(help_text="Emoji character representing the reaction (e.g., '🔥', '👁', '✊')", max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=app.models.base_model.generate_uid,
                        editable=False,
                        help_text="Short, URL-friendly unique identifier.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("content", models.JSONField(verbose_name="Content of the thread")),
                ("text", models.TextField(help_text="Text of the thread.")),
                ("visibility", models.BooleanField(default=True, help_text="This thread can be indexed by the feed.")),
                ("expire_date", models.DateTimeField(blank=True, help_text="Add an expiration date to the thread", null=True)),
                ("momentum_score", models.FloatField(db_index=True, default=0, help_text="Precomputed momentum score (For You ordering).")),
                (
                    "unique_reactors_count",
                    models.PositiveIntegerField(db_index=True, default=0, help_text="Distinct masks that reacted, excluding the author."),
                ),
                (
                    "unique_commenters_count",
                    models.PositiveIntegerField(db_index=True, default=0, help_text="Distinct masks that commented, excluding the author."),
                ),
                ("mask", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="app.mask")),
                (
                    "sub",
                    models.ForeignKey(blank=True, help_text="Parent thread", null=True, on_delete=django.db.models.deletion.CASCADE, to="app.thread"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreadFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=app.models.base_model.generate_uid,
                        editable=False,
                        help_text="Short, URL-friendly unique identifier.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("target_color", models.CharField(default="161c1e", max_length=250)),
                ("width", models.IntegerField(default=0, help_text="Width of the file")),
                ("height", models.IntegerField(default=0, help_text="Height of the file")),
                ("is_video", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(upload_to="uploads/", validators=[django.core.validators.FileExtensionValidator(("mp4", "png", "jpg", "jpeg"))]),
                ),
                ("thread", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.thread")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=app.models.base_model.generate_uid,
                        editable=False,
                        help_text="Short, URL-friendly unique identifier.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=250)),
                ("name_norm", models.CharField(db_index=True, default="", max_length=250)),
                ("thread", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.thread")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReactionRelation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=app.models.base_model.generate_uid,
                        editable=False,
                        help_text="Short, URL-friendly unique identifier.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("mask", models.ForeignKey(help_text="Mask", on_delete=django.db.models.deletion.CASCADE, to="app.mask")),
                ("reaction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.reaction")),
                ("thread", models.ForeignKey(help_text="Reaction thread", on_delete=django.db.models.deletion.CASCADE, to="app.thread")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="mask",
            name="miniature",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.miniature"),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(fields=["-create_at"], name="thread_create_at_desc_idx"),
        ),
    ]
