# Generated by Django 4.2.30 on 2026-06-04 21:08

import app.models.base_model
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentumLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, default=app.models.base_model.generate_uid, editable=False, help_text='Short, URL-friendly unique identifier.', max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('window_days', models.PositiveIntegerField(default=0, help_text='Ventana activa usada en la corrida (--days).')),
                ('processed_count', models.PositiveIntegerField(default=0, help_text='Posts raíz dentro de la ventana evaluados.')),
                ('updated_count', models.PositiveIntegerField(default=0, help_text='Posts cuyos score/contadores cambiaron (bulk_update).')),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Duración total de la corrida en milisegundos.')),
                ('was_successful', models.BooleanField(default=True, help_text='False si la corrida lanzó una excepción.')),
                ('error', models.TextField(blank=True, default='', help_text='Mensaje de la excepción cuando was_successful es False.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
