# Generated by Django 4.2.30 on 2026-06-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_momentumlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-momentum_score', '-create_at'], name='thread_momentum_desc_idx'),
        ),
    ]
