# Generated by Django 4.2.30 on 2026-06-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_thread_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='language',
            field=models.CharField(db_index=True, default='es', help_text="Creator's language from navigator.language (For You filter).", max_length=8),
        ),
        migrations.AlterField(
            model_name='thread',
            name='region',
            field=models.CharField(blank=True, default='', help_text="Creator's country code from navigator.language (For You boost).", max_length=50),
        ),
    ]
