# Generated by Django 4.2.30 on 2026-06-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_normalize_thread_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='geohash',
            field=models.CharField(blank=True, db_index=True, help_text="Author's coarse geohash cell, opt-in (Close You feed).", max_length=12, null=True),
        ),
    ]
