# Generated by Django 4.2.30 on 2026-06-11 23:14

import app.models.base_model
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_thread_geohash4'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, default=app.models.base_model.generate_uid, editable=False, help_text='Short, URL-friendly unique identifier.', max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('name_norm', models.CharField(db_index=True, max_length=250)),
                ('score', models.FloatField(db_index=True, default=0)),
                ('thread_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['-score'], name='trendingtag_score_desc_idx')],
            },
        ),
    ]
