# Generated by Django 4.2.30 on 2026-06-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="threadfile",
            name="file",
        ),
        migrations.RemoveField(
            model_name="threadfile",
            name="height",
        ),
        migrations.RemoveField(
            model_name="threadfile",
            name="target_color",
        ),
        migrations.RemoveField(
            model_name="threadfile",
            name="width",
        ),
        migrations.AddField(
            model_name="threadfile",
            name="file_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Object key in storage (R2/S3 or local media). Reference only.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="threadfile",
            name="file_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Full public URL of the object (client-facing).",
                max_length=600,
            ),
        ),
        migrations.AddField(
            model_name="threadfile",
            name="is_nsfw",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Marked NSFW by the client-side detector (informational).",
            ),
        ),
        migrations.AddField(
            model_name="threadfile",
            name="mask",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.mask",
            ),
        ),
        migrations.AddField(
            model_name="threadfile",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Client-provided config metadata (compression + NSFW). Not EXIF.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="threadfile",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.thread",
            ),
        ),
    ]
