# Generated by Django 4.2.30 on 2026-07-04 16:46

import app.models.base_model
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_threadfile_media_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, default=app.models.base_model.generate_uid, editable=False, help_text='Short, URL-friendly unique identifier.', max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('row_limit', models.PositiveIntegerField(default=0, help_text='Row cap used for the run (--limit).')),
                ('min_age_hours', models.PositiveIntegerField(default=0, help_text='Inactivity age threshold used for the run (--min-age-hours).')),
                ('selected_count', models.PositiveIntegerField(default=0, help_text='Soft-deleted rows picked by the scan (counts against the cap).')),
                ('deleted_count', models.PositiveIntegerField(default=0, help_text='Rows actually removed, cascades included.')),
                ('files_total', models.PositiveIntegerField(default=0, help_text='Storage objects doomed by the run (direct + via cascade).')),
                ('files_removed', models.PositiveIntegerField(default=0, help_text='Storage objects the batched DeleteObjects actually removed.')),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Per-model detail: {"Thread": {"selected": n, "deleted": m}, ...} — only models that had something to purge appear.')),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Total run duration in milliseconds.')),
                ('was_successful', models.BooleanField(default=True, help_text='False if the run raised an exception.')),
                ('error', models.TextField(blank=True, default='', help_text='Exception message when was_successful is False.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
