# Generated by Django 4.2.30 on 2026-07-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_purgelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
            ],
            options={
                'verbose_name': 'System metrics',
                'verbose_name_plural': 'System metrics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.momentumlog',),
        ),
    ]
