# Generated by Django 4.2.30 on 2026-08-07 18:33

import app.models.base_model
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_blockedterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='edited_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of the last content edit (text/media). NULL if never edited.', null=True),
        ),
        migrations.CreateModel(
            name='ThreadEditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, default=app.models.base_model.generate_uid, editable=False, help_text='Short, URL-friendly unique identifier.', max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('previous_text', models.TextField(help_text="The thread's text value immediately BEFORE this edit was applied.")),
                ('media_added_count', models.PositiveSmallIntegerField(default=0, help_text='Number of media files attached to the thread by this specific edit.')),
                ('media_removed_count', models.PositiveSmallIntegerField(default=0, help_text='Number of media files removed from the thread by this specific edit.')),
                ('thread', models.ForeignKey(help_text='The thread (post or reply) this snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='app.thread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
