# Generated by Django 4.2.30 on 2026-08-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_thread_edited_at_threadedithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='Excluded from feed/search — viewable only via direct URL.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_snap',
            field=models.BooleanField(default=False, help_text='Self-deletes 24h after creation (via expire_date). Set only at creation, never editable.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='replies_disabled',
            field=models.BooleanField(default=False, help_text='Owner turned off commenting on this thread.'),
        ),
        migrations.AddField(
            model_name='threadfile',
            name='is_spoiler',
            field=models.BooleanField(db_index=True, default=False, help_text='User-marked spoiler — deliberately hidden, distinct from the automatic is_nsfw flag.'),
        ),
    ]
