# Generated by Django 4.2.30 on 2026-08-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_thread_is_private_thread_is_snap_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadfile',
            options={'ordering': ['create_at', 'id']},
        ),
    ]
