# Generated by Django 4.2.30 on 2026-08-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_threadfile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='unread_notifications_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('reaction', 'Reaction'), ('reply', 'Reply')], db_index=True, max_length=16)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='Who triggered the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.mask')),
                ('reaction', models.ForeignKey(blank=True, help_text='Set only for `reaction` verb.', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.reaction')),
                ('recipient', models.ForeignKey(help_text='Who this notification is for.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.mask')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.thread')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('thread', 'Thread'), ('mask', 'Mask')], max_length=8)),
                ('target_uid', models.CharField(max_length=12)),
                ('day', models.DateField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('qr_count', models.PositiveIntegerField(default=0)),
                ('link_copy_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_uid', '-day'], name='engagement_trend_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='engagementdaily',
            constraint=models.UniqueConstraint(fields=('target_type', 'target_uid', 'day'), name='unique_engagement_per_target_day'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-create_at'], name='notif_recipient_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notif_recipient_unread_idx'),
        ),
    ]
