# Generated by Django 4.2.30 on 2026-08-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thread'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('reaction', 'Reaction'), ('reply', 'Reply'), ('profile_view', 'Profile view'), ('qr_generate', 'QR generate'), ('download', 'Download'), ('share', 'Share'), ('link_copy', 'Link copy')], db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['actor', 'recipient', 'verb', '-create_at'], name='notif_actor_recipient_verb_idx'),
        ),
    ]
