"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

# Python
import hashlib
import hmac
import os
import sys
from pathlib import Path

from corsheaders.defaults import default_headers

# Libs
from decouple import config
from django.core.exceptions import ImproperlyConfigured


def env_list(name: str, default: str = "") -> list[str]:
    """Read a comma-separated env var into a clean list.

    Strips whitespace and drops empty entries (tolerant of trailing commas).
    Example: ALLOWED_HOSTS="localhost, 127.0.0.1" -> ["localhost", "127.0.0.1"].
    """
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def env_required(name: str, description: str = "") -> str:
    """Read a required env var. Raise ImproperlyConfigured if missing/empty.

    Fail-fast at settings import time — the app never starts listening if a
    critical config value is absent.
    """
    value = os.environ.get(name, "").strip()
    if not value:
        hint = f" ({description})" if description else ""
        raise ImproperlyConfigured(
            f"Environment variable '{name}'{hint} is required but is not set "
            f"or is empty. Edit .env and provide a valid value."
        )
    return value


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# API_SECRET_KEY is DERIVED from SECRET_KEY — it is NOT read from the env.
# Both are backend-only secrets at the same trust level, so a single source of
# truth is safe and simpler to manage: configure only SECRET_KEY. Deterministic
# one-way derivation (HMAC-SHA256 with a fixed context label), so the same
# SECRET_KEY always yields the same signing key and already-issued
# client-assertion tickets stay valid across restarts.
# It signs the /ticket/ JWT (see app/methods/tokens.py).
# DO NOT derive GATEWAY_SEED this way: that value is PUBLIC obfuscation (it
# ships in the frontend bundle); binding it to SECRET_KEY would leak the secret.
API_SECRET_KEY = hmac.new(
    SECRET_KEY.encode(),
    b"thiup-api-secret",
    hashlib.sha256,
).hexdigest()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

LOG_LEVEL = "DEBUG" if DEBUG else "INFO"

# Hostnames the server responds to (Host-header attack defense).
# Format: hostnames only — NO scheme, NO port. Wildcards (*.thiup.com) allowed.
ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
)

# Origins trusted for CSRF on cross-origin POSTs (e.g. admin login through nginx).
# Format: full URLs — scheme AND port required (Django 4+ matches exactly).
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:8000,http://localhost:3000",
)

# Origins allowed to make cross-origin browser requests to this backend.
# Note: CORS_ALLOWED_ORIGINS replaces the deprecated CORS_ORIGIN_WHITELIST.
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://localhost:8000",
)

CORS_EXPOSE_HEADERS = ("x-response-payload",)
CORS_ALLOW_HEADERS = default_headers + (
    "client-assertion",
    "x-request-payload",  # sobre del body cifrado del request
    "x-human-pass",  # captcha human pass on entity-creating writes
)

# Real path of the Django admin — REQUIRED. The literal /admin/ is reserved
# as a honeypot decoy; the real admin must live at a non-predictable path.
# Set INTERNAL_ADMIN_URL in .env. App refuses to boot if it's missing or empty.
INTERNAL_ADMIN_URL = env_required(
    "INTERNAL_ADMIN_URL",
    description="Django admin path",
)
# Normalize to Django's path() expectations: no leading slash, trailing slash.
INTERNAL_ADMIN_URL = INTERNAL_ADMIN_URL.lstrip("/")
if not INTERNAL_ADMIN_URL.endswith("/"):
    INTERNAL_ADMIN_URL += "/"
if INTERNAL_ADMIN_URL == "admin/":
    raise ImproperlyConfigured(
        "INTERNAL_ADMIN_URL must not be 'admin/' — that path is reserved for "
        "the honeypot. Set a non-predictable value in .env, e.g. "
        "python -c \"import secrets; print(f'admin-{secrets.token_urlsafe(6)}/')\""
    )

# Security config
ENCRYPTED_RESPONSE = config("ENCRYPTED_RESPONSE", cast=bool)
SINGLE_REQUEST_PROTECT = config("SINGLE_REQUEST_PROTECT", cast=bool)

# The test suite assumes the encrypted transport AND single-request protection
# (the helpers post encrypted bodies with a ticket; some tests assert a 403
# without one). Force both ON under pytest — BEFORE REST_FRAMEWORK below picks
# the renderer — so the suite is independent of the dev .env values (which may
# be off for the local storage adapter). Tests that need them off pin them
# per-test with @override_settings.
if "pytest" in sys.modules:
    ENCRYPTED_RESPONSE = True
    SINGLE_REQUEST_PROTECT = True

# Captcha (Cap standalone, https://github.com/tiagozip/cap): the FE widget
# solves an invisible proof-of-work challenge directly against the Cap server
# and exchanges the resulting single-use token at POST /captcha/verify/ for a
# short-lived, mask-bound "human pass" JWT. Entity-creating writes require the
# pass (see @human_validator in app/permissions/captcha.py). The Cap server
# itself is deployed separately — all coordinates are env-driven.
CAPTCHA_PROTECT = config("CAPTCHA_PROTECT", cast=bool, default=False)
# Lifetime of the human pass. Short: bounds what a bot gains from one solved
# proof-of-work; the FE renews in the background when it expires.
CAPTCHA_PASS_TTL_SECONDS = config("CAPTCHA_PASS_TTL", cast=int, default=600)
# Single local knob: the Cap container binds this port (SERVER_PORT) and
# publishes it 1:1, so both URLs below derive from it. The explicit URL
# overrides exist for a Cap that lives elsewhere (prod). The `or` guard makes
# a present-but-EMPTY env behave like unset (decouple skips its default then),
# so the .env.template can ship these uncommented and blank.
CAP_PORT = config("CAP_PORT", cast=int, default=3333)
# Server-side base URL for the siteverify call (internal hostname is fine).
CAP_SITEVERIFY_URL = config("CAP_SITEVERIFY_URL", default="") or f"http://cap:{CAP_PORT}"
# Browser-facing base URL, exposed via /config/ so the widget can bootstrap.
CAP_PUBLIC_URL = config("CAP_PUBLIC_URL", default="") or f"http://localhost:{CAP_PORT}"
CAP_SITE_KEY = config("CAP_SITE_KEY", default="")
# Backend-only secret — never logged, never echoed, never sent to the FE.
CAP_SECRET = config("CAP_SECRET", default="")

# Opposite pinning to the transport flags above: captcha is forced OFF under
# pytest so the existing suite needs no pass headers; test_captcha.py pins it
# ON per-class with @override_settings and mocks the siteverify call.
if "pytest" in sys.modules:
    CAPTCHA_PROTECT = False

# The URLs always have a derived default; only the key pair has none.
if CAPTCHA_PROTECT and not (CAP_SITE_KEY and CAP_SECRET):
    raise ImproperlyConfigured(
        "CAPTCHA_PROTECT=True requires CAP_SITE_KEY and CAP_SECRET (create them in the Cap dashboard)."
    )

# Seed for the gateway's ROTATING PATH (/{hash}/). Dedicated to deriving the
# path — it does NOT sign anything critical (that is API_SECRET_KEY). It also
# ships in the frontend bundle → it is PUBLIC obfuscation, NOT a secret, and is
# kept strictly independent from SECRET_KEY. Must match the frontend's
# REACT_APP_GATEWAY_SEED. Required: no default, so it is always set explicitly
# and stays in sync with the frontend on purpose.
GATEWAY_SEED = env_required(
    "GATEWAY_SEED",
    description="gateway rotating-path seed; must match the frontend bundle",
)

# Backend logging: the "app" namespace goes to the console with timestamp and
# level (visible in `make logs-web`).
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} — {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "app": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Application definition
PROJECT_APPS = [
    "app",
    "honeypot",
]

EXTERNAL_APPS = ["corsheaders", "drf_yasg", "storages"]

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Required for the __unaccent lookup and the UnaccentExtension migration
    # (accent-insensitive search on PostgreSQL).
    "django.contrib.postgres",
    "rest_framework",
]

INSTALLED_APPS = DJANGO_APPS + EXTERNAL_APPS + PROJECT_APPS

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Descifra el body cifrado del request (espejo del EncodeRenderer) y
    # entrega JSON plano a las vistas — gobernado por ENCRYPTED_RESPONSE.
    "app.middlewares.request_crypto.RequestDecryptMiddleware",
    # (CommonMiddleware was DUPLICATED here — it already runs above; each
    # extra middleware is overhead per request.)
    "app.middlewares.mask.MaskMiddleware",
    "honeypot.middleware.HoneyPotMiddleware",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ── Anti-fingerprinting (defense-in-depth — does NOT replace real
# security: E2E, auth and the obfuscated admin remain the foundation) ───
# Generically named cookies: 'csrftoken'/'sessionid' give Django away to
# Wappalyzer. The FE does not read these cookies (the API uses the
# client-assertion header + E2E), so renaming them is transparent; the admin
# keeps working because Django uses these settings consistently.
CSRF_COOKIE_NAME = config("CSRF_COOKIE_NAME", default="x_t")
SESSION_COOKIE_NAME = config("SESSION_COOKIE_NAME", default="x_s")

# Legitimate security headers (KEPT; they don't reveal the technology).
# Note: the E2E encryption and its X-Response-Payload header are NOT touched.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("DATABASE_ENGINE"),
        "NAME": config("DATABASE_NAME"),
        "USER": config("DATABASE_USER"),
        "HOST": config("DATABASE_HOST"),
        "PORT": config("DATABASE_PORT"),
        "PASSWORD": config("DATABASE_PASSWORD"),
        # Persistent connections: avoids the overhead of opening a Postgres
        # connection on EVERY request (noticeable on limited CPU / Raspberry).
        "CONN_MAX_AGE": 60,
    }
}

REST_FRAMEWORK = {
    "PAGE_SIZE": 25,
    # Rate limit for the ticket issuer (/ticket/, AnonRateThrottle):
    # server-side defense against bootstrap abuse, since it is AllowAny.
    "DEFAULT_THROTTLE_RATES": {
        "anon": "120/min",
        # Búsqueda y autocomplete (ScopedRateThrottle, anónimo por IP).
        # suggest más alto: se dispara al tipear (con debounce en el FE).
        # Ajustables sin tocar código.
        "search": config("THROTTLE_SEARCH", default="60/min"),
        "search_suggest": config("THROTTLE_SUGGEST", default="240/min"),
        # Reports (ScopedRateThrottle, anonymous per IP): cap report abuse.
        "reports": config("THROTTLE_REPORTS", default="30/min"),
        # Entity-creating writes (ScopedRateThrottle, anonymous per IP):
        # bound what a bot achieves within one human-pass window. Generous
        # for humans, hard ceiling for scripts.
        "threads_create": config("THROTTLE_THREADS", default="10/min"),
        "reactions_create": config("THROTTLE_REACTIONS", default="60/min"),
        # Human-pass issuer (/captcha/verify/): renewals are ~1 per TTL per
        # user, so this is far above legitimate traffic.
        "captcha": config("THROTTLE_CAPTCHA", default="20/min"),
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "DEFAULT_RENDERER_CLASSES": [
        "app.renders.encoder.EncodeRenderer" if ENCRYPTED_RESPONSE else "rest_framework.renderers.JSONRenderer",
    ],
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True

# Media
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
MEDIA_URL = "/media/"

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# ─── Media uploads (ThreadFile presign/confirm) ─────────────────────
# SINGLE source of truth for the upload-flow knobs (the storage adapter +
# object_storage read these from settings, not from the env directly). Sensible
# defaults so nothing needs configuring; override via env only if needed.
UPLOAD_PRESIGN_EXPIRES = config("UPLOAD_PRESIGN_EXPIRES", cast=int, default=600)
# General HARD CAP for ANY uploaded object (safety net). The frontend enforces
# finer per-type limits (image 8 MB / GIF 15 MB / video 512 MB) for UX; this is
# the real, untrusted-client guard. In production the upload goes straight to R2
# (Django never holds the bytes) and the cap is checked at confirm via the
# object's actual content-length.
UPLOAD_MAX_BYTES = config("UPLOAD_MAX_BYTES", cast=int, default=512 * 1024 * 1024)
# Keep large file uploads OFF the heap: anything past this small threshold is
# streamed to a temp file on disk by Django (matters for the local debug upload
# view; the R2 path never streams through Django). RAM is limited (~512 MB).
FILE_UPLOAD_MAX_MEMORY_SIZE = config("FILE_UPLOAD_MAX_MEMORY_SIZE", cast=int, default=2 * 1024 * 1024)
# Non-file request body cap (form fields / JSON). Uploaded file parts are NOT
# counted against this — they spill to disk per the setting above.
DATA_UPLOAD_MAX_MEMORY_SIZE = config("DATA_UPLOAD_MAX_MEMORY_SIZE", cast=int, default=5 * 1024 * 1024)
# Object-key layout: "<prefix>/<shard>/.../<token>.<ext>", sharded by the first
# chars of the random token. Hardcoded (not env): purely organizational —
# security comes from the long random token, not the path.
STORAGE_KEY_PREFIX = "m"
STORAGE_SHARD_LEVELS = 2
STORAGE_SHARD_WIDTH = 2

USE_AWS_STORAGE = config("USE_AWS_STORAGE", cast=bool)

print("Use S3 storage system :", "YES" if USE_AWS_STORAGE else "NO")

if USE_AWS_STORAGE:
    from botocore.config import Config

    # Empty -> None. On AWS S3 the keys can be omitted to use the ECS task role;
    # S3-compatible providers (Cloudflare R2) have no IAM, so keys are required.
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default="") or None
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default="") or None
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_CUSTOM_DOMAIN = config("AWS_S3_CUSTOM_DOMAIN")
    # R2 uses the literal region "auto"; AWS S3 set it to your bucket region.
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="auto")
    # Custom endpoint -> S3-compatible provider (e.g. R2). Empty -> native AWS S3.
    AWS_S3_ENDPOINT_URL = config("AWS_S3_ENDPOINT_URL", default="") or None

    AWS_S3_USE_SSL = True
    AWS_S3_VERIFY = True
    # Public, non-expiring URLs for assets (admin/swagger/DRF static + media):
    # no per-object ACLs and no querystring signing.
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    # R2 rejects boto3's default integrity checksums; only send them when the
    # operation requires it. Harmless against native S3.
    AWS_S3_CLIENT_CONFIG = Config(
        request_checksum_calculation="when_required",
        response_checksum_validation="when_required",
    )

    STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
else:
    # Local media: emit absolute URLs so consumers (frontend, emails, admin)
    # see the same shape they get from S3/R2. Origin comes from MEDIA_BASE_URL.
    DEFAULT_FILE_STORAGE = "app.storages.AbsoluteUrlFileSystemStorage"
    MEDIA_BASE_URL = os.environ.get("MEDIA_BASE_URL", "http://localhost:8000")

# Under pytest, never touch real object storage: media goes to an in-memory
# backend so a connected bucket (R2/S3) is never written to, and static resolves
# locally. Overrides whatever the storage block set above.
if "pytest" in sys.modules:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.InMemoryStorage"
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

GEOLITE_DIR = "geolite2-country.mmdb"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
