# Generated by Django 4.2.30 on 2026-05-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Miniature",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default="Empty",
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                (
                    "icon",
                    models.ImageField(
                        help_text="Mask miniature icon",
                        upload_to="miniature",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Mask",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default="Empty",
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("hash", models.CharField(max_length=250, unique=True)),
                (
                    "country_code",
                    models.CharField(
                        help_text="Country of mask",
                        max_length=50,
                    ),
                ),
                (
                    "miniature",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="masks.miniature",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
