# Generated by Django 4.2.30 on 2026-05-23 20:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default="Empty",
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        verbose_name="Content of the thread",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Text of the thread.",
                    ),
                ),
                (
                    "visibility",
                    models.BooleanField(
                        default=True,
                        help_text="This thread can be indexed by the feed.",
                    ),
                ),
                (
                    "expire_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Add an expiration date to the thread",
                        null=True,
                    ),
                ),
                (
                    "mask",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masks.mask",
                    ),
                ),
                (
                    "sub",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent thread",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="threads.thread",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThreadFile",
            fields=[
                ("is_active", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default="Empty",
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("target_color", models.CharField(default="161c1e", max_length=250)),
                ("width", models.IntegerField(default=0, help_text="Width of the file")),
                ("height", models.IntegerField(default=0, help_text="Height of the file")),
                ("is_video", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("mp4", "png", "jpg", "jpeg"),
                            ),
                        ],
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="threads.thread",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
